spring.application.name=demo

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3307/demo?createDatabaseIfNotExist=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.secret=rlMacl968DaaKtd3lsbETdipJp44qhkp8wieT5UUos9IsS8vgRHAHBVTI8thcIQD
arquivamento.path=C:\Users\israel_erthal\Documents\israel\arquivos